[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = "update_hand_text({sound = 'button', volume = 0.7, pitch = 1.1, delay = 0}, vals_after_level or {mult = 0, chips = 0, handname = '', level = ''})"
position = "before"
payload = '''
if args.level_up and args.from.edition then
    for k, v in ipairs(args.hands) do
		Engulf.ApplyEdition(args.from, v, args.level_up or 1, args.instant)
	end 
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = "if not instant and not displayed then"
position = "before"
payload = '''
if args.instant and args.level_up and args.from.edition then
    for k, v in ipairs(args.hands) do
		Engulf.ApplyEdition(args.from, v, args.level_up or 1, args.instant)
	end
end
'''
match_indent = true