[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = "if not instant then delay(1.3) end"
position = "before"
payload = '''
if args.level_up and args.from and args.from.edition and not Engulf.table_contains(Engulf.EditionBlacklist, args.from.edition.key) then
	Engulf.ApplyEdition(args.from, hand, args.level_up or 1, instant) 
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = "if not instant and not displayed then"
position = "before"
payload = '''
if instant and args.level_up and args.from and args.from.edition and not Engulf.table_contains(Engulf.EditionBlacklist, args.from.edition.key) then
    for k, v in ipairs(args.hands) do
		Engulf.ApplyEdition(args.from, v, args.level_up or 1, instant)
	end
end
'''
match_indent = true